myhomepage/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField, RadioField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
	category_id = SelectField('Category',
		choices=[('1', 'Fitness'), ('2', 'Software'), ('3', 'Music'), ('4', 'Miscellaneous')])
	title = StringField('Title', validators=[DataRequired()])
	content = TextAreaField('Content', validators=[DataRequired()])

	mediatype = RadioField('Media Type',
		choices=[('NONE', 'None'), ('VIDEO', 'YouTube Video')],
		default='NONE')
	video_link = StringField('Video Link')

	submit = SubmitField('Post')

myhomepage/main/routes.py
from flask import Blueprint

from flask import render_template, request
from myhomepage.models import Post, User
from myhomepage.practice1 import completePoem
from myhomepage.yt_embed import getVideoID

main = Blueprint('main', __name__)


@main.context_processor
def inject_user():
	return dict(superuser=User.query.filter_by(email='robertoclaure@gmail.com').first())


@main.route("/poem/")
def poem():
	content = completePoem()
	video = getVideoID("https://www.youtube.com/watch?v=Isb7Q4jEA04")
	# return render_template('poemPage.html', authorValue=author, poemBody=poemLines)
	return render_template('poemPage.html', content=content, video=video)


@main.route("/")
@main.route("/home/")
def home():
	page = request.args.get('page', 1, type=int)
	posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
	return render_template('home.html', posts=posts.items, pages=posts)

myhomepage/posts/routes.py
from flask import Blueprint
from flask import render_template, url_for, flash, redirect, request, abort
from flask_login import current_user, login_required
from myhomepage import db
from myhomepage.models import Post, User
from myhomepage.posts.forms import PostForm

from myhomepage.yt_embed import getVideoID

posts = Blueprint('posts', __name__)

@posts.context_processor
def inject_user():
	return dict(superuser=User.query.filter_by(email='robertoclaure@gmail.com').first())


@posts.route("/post/new/", methods=['GET', 'POST'])
@login_required
def new_post():
	form = PostForm()
	if form.validate_on_submit():
		yt_vid_id = getVideoID(form.video_link.data)
		post = Post(category_id= form.category_id.data, title=form.title.data,
				content=form.content.data, author=current_user, yt_link=yt_vid_id)
		db.session.add(post)
		db.session.commit()
		flash('Your post has been created!', 'success')
		return redirect(url_for('main.home'))
	return render_template('create_post.html', title='New Post',
		form=form, legend='New Post')


@posts.route("/post/<int:post_id>/")
def post(post_id):
	post = Post.query.get_or_404(post_id)
	return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update/", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
	post = Post.query.get_or_404(post_id)
	if post.author != current_user:
		abort(403)

	if post.yt_link:
		form = PostForm(category_id=post.category_id,
		mediatype="VIDEO",
		video_link="www.youtube.com/watch?v=" + post.yt_link)
	else:
		form = PostForm(category_id=post.category_id)

	if form.validate_on_submit():
		post.category_id = form.category_id.data
		post.title = form.title.data
		post.content = form.content.data
		if form.video_link.data:
			post.yt_link = getVideoID(form.video_link.data)
		db.session.commit()
		flash('Post has been updated!', 'success')
		return redirect(url_for('posts.post', post_id=post.id))
	elif request.method == 'GET':
		form.title.data = post.title
		form.content.data = post.content
	return render_template('create_post.html', title='Update Post',
		form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete/", methods=['POST'])
@login_required
def delete_post(post_id):
	post = Post.query.get_or_404(post_id)
	if post.author != current_user:
		abort(403)
	db.session.delete(post)
	db.session.commit()
	flash('Post has been deleted!', 'success')
	return redirect(url_for('main.home'))

myhomepage/users/routes.py
from flask import Blueprint
from flask import render_template, url_for, flash, redirect, request
from flask_login import current_user, login_required, logout_user, login_user
from myhomepage import db, bcrypt
from myhomepage.models import User, Post
from myhomepage.users.forms import (RegistrationForm, LoginForm,
	UpdateAccountForm, RequestResetForm, ResetPasswordForm)
from myhomepage.users.utils import save_picture, send_reset_email


users = Blueprint('users', __name__)

@users.context_processor
def inject_user():
	return dict(superuser=User.query.filter_by(email='robertoclaure@gmail.com').first())


@users.route("/register/", methods=['GET', 'POST'])
def register():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RegistrationForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user = User(username=form.username.data, email=form.email.data, password=hashed_password)
		db.session.add(user)
		db.session.commit()
		flash(f'Account created for {form.username.data}!', 'success')
		return redirect(url_for('users.login'))
	return render_template('register.html', title='Register', form=form)


@users.route("/login/", methods=['GET', 'POST'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		if user and bcrypt.check_password_hash(user.password, form.password.data):
			login_user(user, remember=form.remember.data)
			next_page = request.args.get('next')
			return redirect(next_page) if next_page else redirect(url_for('main.home'))
		else:
			flash('Login Unsuccessful. Please check email and password', 'danger')
	return render_template('login.html', title='Login', form=form)


@users.route("/logout/")
def logout():
	logout_user()
	return redirect(url_for('main.home'))


@users.route("/account/", methods=['GET', 'POST'])
@login_required
def account():
	form = UpdateAccountForm()
	if form.validate_on_submit():
		if form.image_file.data:
			picture_file = save_picture(form.image_file.data)
			current_user.image_file = picture_file
		current_user.username = form.username.data
		current_user.email = form.email.data
		current_user.tagline = form.tagline.data
		db.session.commit()
		flash('Your account has been updated!', 'success')
		return redirect(url_for('users.account'))
	elif request.method == 'GET':
		form.username.data = current_user.username
		form.email.data = current_user.email
		form.tagline.data = current_user.tagline
	image_file = url_for('static', filename='images/profilepic/' + current_user.image_file)
	return render_template('account.html', title='Account',
		image_file=image_file,
		form=form)



@users.route("/reset_password/", methods=['GET', 'POST'])
def reset_request():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RequestResetForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		send_reset_email(user)
		flash('An email has been sent with instructions to reset your password.', 'info')
		return redirect(url_for('users.login'))
	return render_template('reset_request.html', title='Reset Password', form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	user = User.verify_reset_token(token)
	if user is None:
		flash('That is an invalid or expired token', 'warning')
		return redirect(url_for('users.reset_request'))
	form = ResetPasswordForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user.password = hashed_password
		db.session.commit()
		flash('Your password has been updated! You are now able to log in', 'success')
		return redirect(url_for('users.login'))
	return render_template('reset_token.html', title='Reset Password', form=form)

myhomepage/templates/account.html
{% extends "base.html" %}
{% block content %}
	<h1>{{ current_user.username }}</h1>
	<div class="site-post">
		<div class="media">
			<img class="rounded-circle" style="width:200px; height:200px;" src="{{ image_file }}">
			<div class="media-body">
				<h2>{{ current_user.username }}</h2>
				<p>{{ current_user.email }}</p>
			</div>
		</div>
		<form method="POST" action="" enctype="multipart/form-data">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Account Info</legend>
				<div class="form-group">
					{{ form.username.label(class="form-control-label") }}

					{% if form.username.errors %}
						{{ form.username(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{%for error in form.username.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.username(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{%for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.tagline.label(class="form-control-label") }}
					{% if form.tagline.errors %}
						{{ form.tagline(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{%for error in form.tagline.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.tagline(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.image_file.label() }}
					{{ form.image_file(class="form-control-file") }}
					{% if form.image_file.errors %}
						{% for error in form.image_file.errors %}
							<span class="text-danger">{{ error }}</span></br>
						{% endfor %}
					{% endif %}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
	</div>
{% endblock content %}

myhomepage/templates/base.html
<!DOCTYPE html>
<html>
<head>

	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">

	<title>Base For Now</title>
</head>
<body>
    <!-- <div class="site-container"> -->

    <header class="site-header container-fluid">
        <div class="row wrap px-0">
            <div class="col-auto site-avatar my-auto px-0">
                <img src="/static/images/profilepic/{{ superuser.image_file }}" class="img-responsive center-block rounded-circle" style="width: 200px; height: 200px">
            </div>
            <div class="col site-title my-auto">
                <h1>Roberto Claure</h1>
                <h3 class="text-muted">{{ superuser.tagline }}</h3>
            </div>
            <div class="col social-media-area my-auto text-right">
                <h3>Todo: Insert SM Links</h3>
                <h4 class="text-muted">Twitter, IG, etc.</h4>
            </div>
        </div>
    </header>

    <nav class="navbar navbar-expand-md navbar-dark" style="background-color: #850000">
        <div class="row wrap px-0">
            <a class="navbar-brand" href="{{ url_for('main.home') }}">RC</a>
            <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="{{ url_for('main.home') }}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.poem') }}">Poem</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">TBD</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">TBD</a>
                    </li>
                    <li class="nav-item">
                        {% if current_user.is_authenticated %}
                            <a class="nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                            <a class="nav-link" href="{{ url_for('users.account') }}">Account</a>
                            <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                        {% else %}
                            <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </nav>

	<main role="main" class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-10">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                {% block content %}{% endblock %}
            </div>
        </div>
	</main>

    <!-- </div> -->


	<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script type="text/javascript">
    function setWidth() {
        document.getElementById("ytplayer").style.width = '100%';
        var vidWidth = document.getElementById("ytplayer").offsetWidth;
        var newHeightValue = (vidWidth / 16) * 9;
        var txtHeight = newHeightValue + "px";
        document.getElementById("ytplayer").style.height = txtHeight;
    }

    </script>
</body>
</html>

myhomepage/templates/create_post.html
{% extends "base.html" %}
{% block content %}
	<div class="site-post">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">{{ legend }}</legend>

				<div class="form-group">
					{{ form.category_id.label(class="form-control-label") }}
					{{ form.category_id(class="form-control form-control-lg") }}
				</div>

				<div class="form-group">
					{{ form.title.label(class="form-control-label") }}
					{% if form.title.errors %}
						{{ form.title(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{%for error in form.title.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.title(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.content.label(class="form-control-label") }}
					{% if form.content.errors %}
						{{ form.content(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.content.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.content(class="form-control form-control-lg") }}
					{% endif %}
				</div>

				<div class="form-group">
					{{ form.mediatype.label(class="form-control-label") }}
					{{ form.mediatype }}

					<div id="link-field">
						{{ form.video_link.label(class="form-control-label") }}
						{{ form.video_link (class="form-control form-control-lg", placeholder="www.youtube.com/") }}
					</div>
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
	</div>
{% endblock content %}

myhomepage/templates/home.html
{% extends "base.html" %}
{% block content %}

	{% for post in posts %}
		<article class="media site-post blog-post">
			<img class="rounded article-img" src="{{ url_for('static', filename='images/' + post.post_category.image_file) }}">
			<div class="media-body">
				<div class="article-metadata">
					<!-- <a class="mr-2" href="#">{{ post.author.username }}</a> -->
		      		<small class="text-muted">{{ post.date_posted.strftime('%d %b, %Y') }}</small>
				</div>
				<h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
		    	<p class="article-content">{{ post.content }}</p>
			</div>
		</article>
	{% endfor %}

	{% for page_num in pages.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
		{% if page_num %}
			{% if pages.page == page_num %}
				<a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num)}}">{{ page_num }}</a>
			{% else %}
				<a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num)}}">{{ page_num }}</a>
			{% endif %}
		{% else %}
			...
		{% endif %}
	{% endfor %}

{% endblock content %}

myhomepage/templates/login.html
{% extends "base.html" %}
{% block content %}
	<div class="site-post">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Log In</legend>

				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{%for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.password.label(class="form-control-label") }}
					{% if form.password.errors %}
						{{ form.password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{%for error in form.password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.password(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-check">
					{{ form.remember(class="form-check-input") }}
					{{ form.remember.label(class="form-check-label") }}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
				<small class="text-muted ml-2">
					<a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
				</small>
			</div>

		</form>
	</div>
	<div class="border-top pt-3">
		<small class="text-muted">
			Don't Have An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
		</small>
	</div>
{% endblock content %}

myhomepage/templates/poemPage.html
{% extends "base.html" %}
{% block content %}

	<div class="site-post">

		<a data-flickr-embed="true" href="https://www.flickr.com/photos/9somboon/35071348993/" title="Big Yor at PakPra Thailand by Somboon Kaeoboonsong, on Flickr"><img src="https://live.staticflickr.com/4205/35071348993_39e6733199_b.jpg" width="100%" alt="Big Yor at PakPra Thailand"></a><script async src="https://embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>

		<iframe onload="setWidth()" id="ytplayer" type="text/html" src="https://youtube.com/embed/{{ video }}"></iframe>

		


	</div>

	<h1>{{ content.poemAuthor }}</h1>
	{% for line in content.poemBody %}
		<li>{{ line }}</li>
	{% endfor %}

{% endblock content %}

myhomepage/templates/post.html
{% extends "base.html" %}
{% block content %}

	<article class="media site-post blog-post">
		<img class="rounded article-img" src="{{ url_for('static', filename='images/' + post.post_category.image_file) }}">
		<div class="media-body">
			<div class="article-metadata">
	      		<small class="text-muted">{{ post.date_posted.strftime('%d %b, %Y') }}</small>
	      		{% if post.author == current_user %}
	      			<div>
	      				<a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id = post.id) }}">Update</a>
	      				<button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
	      			</div>
	      		{% endif %}
			</div>
			<h2 class="article-title">{{ post.title }}</a></h2>
	    	<p class="article-content">{{ post.content }}</p>
	    	{% if post.yt_link %}
	    		<iframe onload="setWidth()" id="ytplayer" type="text/html" src="https://youtube.com/embed/{{ post.yt_link }}"></iframe>
	    	{% endif %}
		</div>
	</article>

	<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
	        <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
	        	<input class="btn btn-danger" type="submit" value="Delete">
	        </form>
	      </div>
	    </div>
	  </div>
	</div>
{% endblock content %}

myhomepage/templates/register.html
{% extends "base.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Join Today</legend>
				<div class="form-group">
					{{ form.username.label(class="form-control-label") }}

					{% if form.username.errors %}
						{{ form.username(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{%for error in form.username.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.username(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{%for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.password.label(class="form-control-label") }}
					{% if form.password.errors %}
						{{ form.password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{%for error in form.password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.password(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.confirm_password.label(class="form-control-label") }}
					{% if form.confirm_password.errors %}
						{{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{%for error in form.confirm_password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.confirm_password(class="form-control form-control-lg") }}
					{% endif %}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
	</div>
	<div class="border-top pt-3">
		<small class="text-muted">
			Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
		</small>
	</div>
{% endblock content %}

myhomepage/templates/reset_request.html
{% extends "base.html" %}
{% block content %}
	<div class="site-post">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Reset Password</legend>
				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{%for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
	</div>
{% endblock content %}

myhomepage/templates/reset_token.html
{% extends "base.html" %}
{% block content %}
	<div class="site-post">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Reset Password</legend>
				<div class="form-group">
					{{ form.password.label(class="form-control-label") }}
					{% if form.password.errors %}
						{{ form.password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{%for error in form.password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.password(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.confirm_password.label(class="form-control-label") }}
					{% if form.confirm_password.errors %}
						{{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{%for error in form.confirm_password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.confirm_password(class="form-control form-control-lg") }}
					{% endif %}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
	</div>
{% endblock content %}